version: "3"

services:
  app:
    build: ./app
    container_name: {% cookiecutter.project_name | slugify(separator='_') %}
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - SERVICE={% cookiecutter.project_name | slugify(separator='_') %}
      - IN_DOCKER=yes
    volumes:
      - ./log:/var/log
